version: '2.1'
services:
  web:
    build: .
    environment:
      APP_USERNAME: "${APP_USERNAME:-username}"
      APP_PASSWORD: "${APP_PASSWORD:-password}"
      DB_HOST: "${DB_HOST:-db}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_USERNAME: "${DB_USERNAME:-releaseserver}"
      DB_NAME: "${DB_NAME:-releaseserver}"
      DB_PASSWORD: "${DB_PASSWORD:-secret}"
      TOKEN_SECRET: "${TOKEN_SECRET:-change_me_in_production}"
      APP_URL: "${APP_URL:-localhost:5000}"
    depends_on:
      - db
    ports:
      - '5000:80'
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_USER: "${DB_USERNAME:-releaseserver}"
      POSTGRES_DB: "${DB_NAME:-releaseserver}"
    ports:
      - '5432:5432'
